name: neeleez_b2b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/
    - assets/svgs/
    - assets/pngs/

  uses-material-design: true

