name: neeleez_b2b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  fl_chart: ^0.60.0
  flutter_rating_bar: ^4.0.1
  dio: ^5.0.1
  flutter_spinkit: ^5.1.0
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/
    - assets/svgs/
    - assets/pngs/
    - assets/fonts/

  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf

  uses-material-design: true

